PACKAGES: IVS_TVAC

ThermalVac:
    HOSTNAME:           localhost
    PORT:               4840
    SETPOINT_TEMP_MIN:  -70      # Minimum temperature setpoint [°C]
    SETPOINT_TEMP_MAX:  80       # Maximum temperature setpoint [°C]


ThermalVac Control Server:
    PROTOCOL:           tcp
    HOSTNAME:           localhost
    COMMANDING_PORT:    0          # The port on which the controller listens to commands - REQ-REP
    MONITORING_PORT:    0          # The port on which the controller sends periodic status information of the device - PUB-SUB
    SERVICE_PORT:       0          # The port on which the controller listens for configuration and administration - REQ-REP
    METRICS_PORT:       0          # The HTTP port where Prometheus will connect to for retrieving metrics
    SAMPLE_INTERVAL:    5          # Time between subsequent scans [s]
    SERVICE_TYPE:       TVAC
    SERVICE_NAME:       TVAC
    STORAGE_MNEMONIC:   TVAC

