on:
  push:
    branches:
      - main

jobs:
  my_first_job:
    name: Run Ruff on cgse-common
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: libs/cgse-common/src
